### ISSUE TITLE
can't get it to work with gradle 4.x..

### ISSUE THREAD

**Issue by eitansuez** [mdietrichstein/gradle-offline-dependencies-plugin#1]
hi there.  thanks for this awesome work.  i noticed i can get it to work with gradle 3.5 but not 4.x, not sure why.

**Comment by mdietrichstein** [comment]
Hi @eitansuez,

Thanks for the heads up! I've pushed a fix (https://github.com/mdietrichstein/gradle-offline-dependencies-plugin/commit/ae28bb959fb32e530f3da64801f3107732d9de87) that should make the plugin compatible with gradle 4.x.

**Comment by eitansuez** [comment]
wonderful.  thanks.  i'll likely try it out next week.
/ eitan

**Comment by omarbelkhodja** [comment]
I think it still doesn't work. This is the result I have : (Windows + Cygwin)

./gradlew updateOfflineRepository -PofflineRepositoryRoot=./offline-repository
:updateOfflineRepository FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':updateOfflineRepository'.
> Could not resolve all dependencies for configuration ':detachedConfiguration1'.
   > Cannot resolve external dependency gradle.plugin.io.pry.gradle.offline_dependencies:gradle-offline-dependencies-plugin:0.3 because no repositories are defined.
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed


My build.gradle is :
buildscript {
  repositories {
    maven {
      url offlineRepositoryRoot
    }
    maven {
      url 'https://plugins.gradle.org/m2/'
    }
    mavenCentral()
    jcenter()
    google()
  }

  dependencies {
    classpath 'gradle.plugin.io.pry.gradle.offline_dependencies:gradle-offline-dependencies-plugin:0.3'
    classpath 'com.android.tools.build:gradle:3.0.1'
  }
}

apply plugin: 'io.pry.gradle.offline_dependencies'

**Comment by k-mack** [comment]
@omarbelkhodja I'm experiencing the same error. I'm running Gradle 4.2.1 on Linux. Did you manage to resolve this?
